Traceback (most recent call last):
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kthyng/miniconda3/envs/ciofs/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
getattr(chr.src.plot_dataset_on_map, "ctd_towed_ferry_noaa_pmel")("ctd_towed_ferry_noaa_pmel")
        
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [38;5;28;43mgetattr[39;49m[43m([49m[38;5;28;43mchr[39;49m[38;5;241;43m.[39;49m[43msrc[49m[38;5;241;43m.[39;49m[43mplot_dataset_on_map[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mctd_towed_ferry_noaa_pmel[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mctd_towed_ferry_noaa_pmel[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/projects/ciofs-hindcast-report/ciofs_hindcast_report/src/plot_dataset_on_map.py:181[0m, in [0;36mctd_towed_ferry_noaa_pmel[0;34m(slug)[0m
[1;32m    177[0m two_maps [38;5;241m=[39m [38;5;28mdict[39m(extent_left[38;5;241m=[39m[38;5;28mchr[39m[38;5;241m.[39mextent_whole, extent_right[38;5;241m=[39m[[38;5;241m-[39m[38;5;241m156[39m, [38;5;241m-[39m[38;5;241m150.5[39m, [38;5;241m57[39m, [38;5;241m59.75[39m],
[1;32m    178[0m                 width_ratios[38;5;241m=[39m[[38;5;241m0.4[39m, [38;5;241m1.6[39m])
[1;32m    180[0m cat [38;5;241m=[39m intake[38;5;241m.[39mopen_catalog([38;5;28mchr[39m[38;5;241m.[39mCAT_NAME(slug [38;5;241m+[39m [38;5;124m"[39m[38;5;124m_initial[39m[38;5;124m"[39m))
[0;32m--> 181[0m ds [38;5;241m=[39m [43mcat[49m[43m[[49m[43mslug[49m[43m][49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mdoresampling[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[38;5;241m.[39mcf[38;5;241m.[39msel(T[38;5;241m=[39m[38;5;28mslice[39m([38;5;28;01mNone[39;00m,[38;5;28;01mNone[39;00m, [38;5;241m500[39m))
[1;32m    183[0m maps [38;5;241m=[39m np[38;5;241m.[39mvstack((ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlongitude[39m[38;5;124m"[39m][38;5;241m.[39mvalues, ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlongitude[39m[38;5;124m"[39m][38;5;241m.[39mvalues, 
[1;32m    184[0m                   ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlatitude[39m[38;5;124m"[39m][38;5;241m.[39mvalues, ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlatitude[39m[38;5;124m"[39m][38;5;241m.[39mvalues,
[1;32m    185[0m                   [[38;5;124m"[39m[38;5;124m"[39m] [38;5;241m*[39m [38;5;28mlen[39m(ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlongitude[39m[38;5;124m"[39m]),
[1;32m    186[0m                   [[38;5;124m"[39m[38;5;124mpoint[39m[38;5;124m"[39m] [38;5;241m*[39m [38;5;28mlen[39m(ds[38;5;241m.[39mcf[[38;5;124m"[39m[38;5;124mlongitude[39m[38;5;124m"[39m]),
[1;32m    187[0m                  ))[38;5;241m.[39mT
[1;32m    189[0m omsa[38;5;241m.[39mplot[38;5;241m.[39mmap[38;5;241m.[39mplot_map(maps,
[1;32m    190[0m                        figname[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mMap of [39m[38;5;132;01m{[39;00mslug[38;5;132;01m}[39;00m[38;5;124m"[39m,
[1;32m    191[0m                               label_with_station_name[38;5;241m=[39m[38;5;28;01mTrue[39;00m, 
[0;32m   (...)[0m
[1;32m    196[0m                               annotate[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    197[0m                        )

[0;31mTypeError[0m: DatasetTransform.read() got an unexpected keyword argument 'doresampling'
TypeError: DatasetTransform.read() got an unexpected keyword argument 'doresampling'

